### ISSUE TITLE
Theme: Gallery View Search Results

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#146] opened 2024-10-08 18:45 UTC
## Summary
There are several discrepancies between the Gallery View of Search Results on Knapsack versus Hyku Commons:
- Items are not equal in size and space 
- Only some items have boxes around them
- User has to horizontally scroll to view all items
- There is an image underneath the two right-most items
- Knapsack is not responsive

### [Knapsack](https://demo.palni-palci-staging.notch8.cloud/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=)

https://github.com/user-attachments/assets/f766ff8b-4a08-43e9-a973-ee699d044810

### [HykuCommons](https://demo.hykucommons.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=)

https://github.com/user-attachments/assets/61db376b-41bc-4f8a-bc5a-e874d5a3b23b

## Acceptance Criteria
- [ ] Items are equally spaced and are equal in size
- [ ] Items have boxes around them
- [ ] User only needs to vertically scroll to view items
- [ ] Knapsack is responsive like HykuCommons

**Comment by jillpe** [comment] 2024-11-20 17:24
This was resolved with the most recent update.

**Comment by laritakr** [comment] 2024-12-02 22:19
Closing - duplicate of https://github.com/scientist-softserv/palni_palci_knapsack/issues/174

**Closed by laritakr** 2024-12-02 22:19 UTC
Labels: High Priority
