### ISSUE TITLE
UV is not functional

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#44] opened 2024-05-30 23:18 UTC
## Summary
The UV screen goes black and does not display the work. 

![image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/84697174/4ef360f1-08a3-4386-9d07-215df63da782)

## Acceptance Criteria
- [ ] The UV displays the work

**Comment by ShanaLMoore** [comment] 2024-06-03 17:11
@jillpe in the future could you provide a link to your screenshots? This can help us save time when trying to find and reproduce the issue.

**Comment by ShanaLMoore** [comment] 2024-06-03 17:18
In the given [example](https://demo.palni-palci-staging.notch8.cloud/concern/images/c2f44868-54a2-40e4-b197-daf869002cdf?locale=en), 

The UV isn't displaying because the work is a pdf, and the works did not split (because that code hasn't been merged into hyku yet). 

When switching the feature flipper to PDF.js, the work renders: 



![Image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/10081604/7b9f9651-7c6d-40a5-9461-0c93de163088)

When choosing a [work](https://demo.palni-palci-staging.notch8.cloud/concern/images/a1fa505f-3b68-488d-b98d-d56393f076fc?locale=en) with a jpg attachment, the UV renders as expected: 



![Image](https://github.com/scientist-softserv/palni_palci_knapsack/assets/10081604/f11f4326-e9ce-477a-a2dd-2f9623d05120)

**Closed** 2024-06-03 17:19 UTC
Labels: High Priority, bug
