### ISSUE TITLE
Collection Show Page

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/palni_palci_knapsack#155] opened 2024-10-09 16:48 UTC
## Summary
The 'sort by', 'results per page', 'refresh', and item formatting buttons do not look the same as HykuCommons. See screenshot

### Knapsack
![Image](https://github.com/user-attachments/assets/7c10908d-4e03-4dd9-b05c-d036103d5167)

### HykuCommons
![Image](https://github.com/user-attachments/assets/1a100693-7d01-4a03-aafe-578a5da783c9)

## Acceptance Criteria
- [ ] The 'sort by', 'results per page', 'refresh', and item formatting buttons on the collection page resemble the HykuCommons version

**Comment by laritakr** [comment] 2024-12-02 21:49
Duplicate of https://github.com/scientist-softserv/palni_palci_knapsack/issues/137

**Closed** 2024-12-02 22:14 UTC
Labels: High Priority
